### ISSUE TITLE
command line options

### ISSUE THREAD

**Issue by 2play** [hatari/hatari#3]
hello to all

thank you for the great work

I have created 3 config files. 2 for Falcon and 1 for tt.
saved as falcon4.cfg falcon14.cfg tt.cfg
i tried to apply via the option c, --configfile <filename> as below example but emu goes back to ES

`hatari-fast = "/opt/retropie/emulators/hatari/bin/hatari --confirm-quit 0 --statusbar 0 --zoom 1 -w --compatible 0 --timer-d 1 --borders 0 --configfile tt.cfg -f %ROM%"`

even with full path of the file wont start.

If i put in the /bin it works ONLY from the cli but not above

is it common to have at cli after run
`INFO : Hatari v2.2.1, compiled on:  May 23 2019, 14:47:09
INFO : Inserted disk '/home/pi/RetroPie/roms/atarist/1943 (1987)(Probe Software).st' to drive A:.
WARN : Bus Error writing at address $81fffe, PC=$e0021a addr_e3=e0021a op_e3=3305
WARN : Bus Error writing at address $ffd000e0, PC=$e00242 addr_e3=e00242 op_e3=33fc
WARN : Bus Error reading at address $fffffc21, PC=$e00c24 addr_e3=e00c24 op_e3=4a10
WARN : Bus Error reading at address $dc03c3, PC=$e00c24 addr_e3=e00c24 op_e3=4a10
WARN : Bus Error reading at address $cc03c3, PC=$e00c24 addr_e3=e00c24 op_e3=4a10`

**Comment by huth** [comment]
Sorry, I have a hard time understanding your problem. What is "ES"? Which TOS version are you using? Do you get any more information when you run Hatari with the option "--log-level debug" ?

**Comment by 2play** [comment]
HI @huth !
Thank you for your reply. Im using hatari on retropie and EmulationStation (ES) frontend.
I have EmuTOS 0.9.10 latest and works fine in normal settings or via cli. 

Initially from cli
`/opt/retropie/emulators/hatari/bin/hatari --confirm-quit 0 --statusbar 0 --zoom 1 -w --compatible 0 --timer-d 1 --borders 0 --configfile tt.cfg -f PATHNAMETOROM`
works fine to load my custom hatari cfg file. (need to be in /bin folder otherwise ddnt work. (i used now symbolic links to the path i want. (so i found for this a solution)

When I use same on the configs/atarist folder to include option for ES to use
`hatari-fast = "/opt/retropie/emulators/hatari/bin/hatari --confirm-quit 0 --statusbar 0 --zoom 1 -w --compatible 0 --timer-d 1 --borders 0 --configfile tt.cfg -f %ROM%"`
it doesnt like the command with the cfg file.
without -c <file> works ok

so its something i guess with --configfile tt.cfg inside " "?

Most errors i find when i run from cli and see the terminal.
I ll try the debug option if ES allows me to see the terminal
Reverting

**Comment by 2play** [comment]
Thank you for you time and help in advance

**Comment by huth** [comment]
You can also try to redirect the log output into a file. Add this to your cfg file:

[Log]
sLogFileName = /home/2play/debug.log
nTextLogLevel = 5

**Comment by 2play** [comment]
added and tested. I think its the c- filename that is not understood inside the " " of the full line.
its not finding the filename at all to process so its nor creating a debug file. 
i have to make it understood inside the " " to pick the file
i know i cant have `hatari-fast = "/opt/retropie/emulators/hatari/bin/hatari --confirm-quit 0 --statusbar 0 --zoom 1 -w --compatible 0 --timer-d 1 --borders 0 --configfile "tt.cfg" -f %ROM%"`

**Comment by huth** [comment]
Sounds like a problem with retropie / ES to me. Please try to discuss this issue with them first.

**Comment by 2play** [comment]
not a problem with ES/RPie.
Just command structure to accept all hatari binary options including the custom cfg. 
I solved it so Im good.
